### PR TITLE
feat: Initial implementation

### PR DESCRIPTION
**Pull request by disq**
Can be tested with:

```bash
SCW_ACCESS_KEY=SCWKEY SCW_SECRET_KEY=00000000-0000-SECRET SCW_DEFAULT_ORGANIZATION_ID=11111111-1111-ORG-ID go run . serve
```

Replacing the access key, secret and default org ID to valid values. For the cli config, set up a regular cloudquery config as described in the README but set a GRPC registry in the source section, like so:

```yaml
kind: source
spec:
  name: scaleway
  version: v0.0.0
  registry: grpc
  path: localhost:7777
  tables:
    - "*"
#  skip_tables:
#    - "scaleway_marketplace_image_versions"
  destinations: ["postgresql"]
  backend: local
  spec:

---
kind: destination
spec:
  name: "postgresql"
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v2.0.10"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/cq" # might need to add ?sslmode=disable
```

(would also need to do a `CREATE DATABASE cq;` in the DB)

### CODE REVIEW

**Comment by remyleone** [comment]
When I'm trying to curl the server I get the following:

```
$ curl http://localhost:7777 
curl: (1) Received HTTP/0.9 when not allowed
```

Is that normal?

**Comment by disq** [comment]
> When I'm trying to curl the server I get the following:
> 
> ```
> $ curl http://localhost:7777 
> curl: (1) Received HTTP/0.9 when not allowed
> ```
> 
> Is that normal?

@remyleone Perfectly normal, you'd need to use CloudQuery CLI which communicates with the plugins using GRPC.
Refer to [Architecture](https://www.cloudquery.io/docs/developers/architecture) and [Running Plugins Locally](https://www.cloudquery.io/docs/developers/running-locally) sections in the developer documentation for details.

**Comment by yevgenypats** [comment]
@remyleone kind ping :) if we can merge this and tag so there will be a first version available and we can iterate from there?

**Comment by remyleone** [comment]
done :)

**Pull request merged**
